const path = require("path")
const HtmlWebpackPlugin = require("html-webpack-plugin")
const FaviconsWebpackPlugin = require("favicons-webpack-plugin")
const {VanillaExtractPlugin} = require('@vanilla-extract/webpack-plugin')

module.exports = {
	entry: "./src/main.tsx",
	output: {
		filename: "main.js",
		path: path.resolve(__dirname, "built"),
	},
	plugins: [
		new HtmlWebpackPlugin({
			template: path.join(__dirname, "static", "index.html"),
		}),
		new FaviconsWebpackPlugin("./static/favicon.ico"),
		new VanillaExtractPlugin(),
	],
	devServer: {
		static: {
			directory: path.join(__dirname, "built"),
		},
		historyApiFallback: true,
		port: 3000,
	},
	module: {
		// exclude node_modules
		rules: [
			{
				test: /\.(js|jsx)$/,
				exclude: /node_modules/,
				use: ["babel-loader"],
			},
			{
				test: /\.(ts|tsx)$/,
				exclude: /node_modules/,
				use: ["ts-loader"],
			},
			{
				test: /\.vanilla\.css$/i, // Targets only CSS files generated by vanilla-extract
				use: [
					{
						loader: require.resolve('css-loader'),
						options: {
							url: false, // Required as image imports should be handled via JS/TS import statements
						},
					},
				],
			},
		],
	},
	// pass all js files through Babel
	resolve: {
		extensions: ["*", ".js", ".jsx", ".ts", ".tsx"],
	},
}
